version: '3'
services:
  react-app:
    image: "node:alpine"
    working_dir: /home/node/app 
    ports:
      - "80:3000"
      - "5000:5000"
    volumes:
      - .:/home/node/app
    command: ["yarn","dev"]
